/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2020-12-21 04:33:09 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class joinMember_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/head.jsp", out, false);
      out.write("\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"css/joinMember.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <!-- <header> -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/header.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- center = <aside> + <article> -->\r\n");
      out.write("    <div class=\"center\">\r\n");
      out.write("        <aside>\r\n");
      out.write("            <p><a href=\"ticket.do\">예약 내역</a></p>         \r\n");
      out.write("            <p><a href=\"editMember.do\">회원 정보 수정</a></p>\r\n");
      out.write("        </aside>\r\n");
      out.write("        \r\n");
      out.write("           \r\n");
      out.write("        <article>        \r\n");
      out.write("         <h1>회원 가입</h1>            \r\n");
      out.write("                    <h3>고객님의 개인 정보는 엄격하게 관리됩니다.</h3>    \r\n");
      out.write("                <form action=\"joinMemberPro.do\" method=\"post\" name=\"frm\" onsubmit=\"return lenCheck()\">\r\n");
      out.write("                \t\r\n");
      out.write("                    <table>\r\n");
      out.write("\t               \t\t<tr>\r\n");
      out.write("\t               \t\t\t<th>아이디 : \r\n");
      out.write("\t               \t\t\t<td><input type=\"text\" name=\"id\" id=\"id\" /></td>\r\n");
      out.write("\t               \t\t\t<td><input type=\"button\" onclick=\"dupCheck()\" value=\"중복체크\"><td>\r\n");
      out.write("\t               \t\t</tr>\r\n");
      out.write("\t               \t\t<tr>\r\n");
      out.write("\t               \t\t\t<th>암호 : \r\n");
      out.write("\t               \t\t\t<td><input type=\"password\" name=\"pswd1\" id=\"pswd1\" required/>\r\n");
      out.write("\t               \t\t</tr>\r\n");
      out.write("\t               \t\t<tr>\r\n");
      out.write("\t               \t\t\t<th>암호 확인 : \r\n");
      out.write("\t               \t\t\t<td><input type=\"password\" name=\"pswd2\" id=\"pswd2\" required onkeyup=\"pwCheck()\"/>\r\n");
      out.write("\t               \t\t\t<td><span id=\"pwStatus\"></span></td>\r\n");
      out.write("\t               \t\t</tr>\r\n");
      out.write("\t               \t\t<tr>\r\n");
      out.write("\t               \t\t\t<th>이름 : \r\n");
      out.write("\t               \t\t\t<td><input type=\"text\" name=\"name\" id=\"name\" required/>\r\n");
      out.write("\t               \t\t</tr>\r\n");
      out.write("\t               \t\t<tr>\r\n");
      out.write("\t               \t\t\t<th>생년월일 : \r\n");
      out.write("\t               \t\t\t<td><input type=\"text\" name=\"birth\" id=\"birth\" required/>\r\n");
      out.write("\t               \t\t</tr>\r\n");
      out.write("\t               \t\t<tr>\r\n");
      out.write("\t               \t\t\t<th>성별 : \r\n");
      out.write("\t               \t\t\t<td><input type=\"radio\" name=\"gender\" id=\"man\" value=\"1\" required />남 &nbsp;\r\n");
      out.write("\t               \t\t\t\t<input type=\"radio\" name=\"gender\" id=\"woman\" value=\"2\" required />여\r\n");
      out.write("\t               \t\t</tr>\r\n");
      out.write("\t               \t\t<tr>\r\n");
      out.write("\t               \t\t\t<th>전화번호 : \r\n");
      out.write("\t               \t\t\t<td><input type=\"text\" name=\"tel\" id=\"tel\" required>\r\n");
      out.write("\t               \t\t</tr>\r\n");
      out.write("\t               \t\t<tr>\r\n");
      out.write("\t               \t\t\t<th>주소 : \r\n");
      out.write("\t               \t\t\t<td><input type=\"text\" name=\"address\" id=\"address\" required>\r\n");
      out.write("\t               \t\t</tr>\r\n");
      out.write("\t               \t\t<tr>\r\n");
      out.write("\t               \t\t\t<td colspan=\"2\" align=\"center\"><input type=\"submit\" name=\"enroll\" class=\"enroll\" value=\"가입\"></td> \r\n");
      out.write("\t               \t\t</tr>\r\n");
      out.write("\t               \t\t<tr>\r\n");
      out.write("\t               \t\t\t<td colspan=\"2\" align=\"center\"><input type=\"reset\" value=\"취소\"></td> \r\n");
      out.write("\t               \t\t</tr>\r\n");
      out.write("               \t\t</table>\r\n");
      out.write("                \r\n");
      out.write("                \r\n");
      out.write("                </form>\r\n");
      out.write("        </article>\r\n");
      out.write("    </div>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <!-- <footer> -->\r\n");
      out.write("    ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/include/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("\tfunction dupCheck() {\r\n");
      out.write("\t\tlet id = document.frm.id.value;\r\n");
      out.write("\t\tif(id == '') {\r\n");
      out.write("\t\t\talert(\"아이디를 입력하세요\");\r\n");
      out.write("\t\t\tdocument.frm.id.focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\twindow.open('joinCheck.do?id='+id, 'joinCheck', 'width=600, height=300');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction lenCheck() {\r\n");
      out.write("\t\tlet id = document.frm.id.value.trim();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(!(id.length >= 3 && id.length <=12)) {\r\n");
      out.write("\t\t\talert(\"아이디는 3에서 12글자만 입력 가능합니다.\");\r\n");
      out.write("\t\t\tdocument.frm.id.select();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tfunction pwCheck() {\r\n");
      out.write("\t\tpw1 = document.frm.pswd1.value;\r\n");
      out.write("\t\tpw2 = document.frm.pswd2.value;\r\n");
      out.write("\t\tpwStatus = document.getElementById(\"pwStatus\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(pw1 == pw2) {\r\n");
      out.write("\t\t\tpwStatus.innerHTML = \"패스워드 확인\";\r\n");
      out.write("\t\t\tpwStatus.style.color = \"blue\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\tpwStatus.innerHTML = \"패스워드 틀림\";\r\n");
      out.write("\t\t\tpwStatus.style.color = \"red\"\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("/* \t<tr>\r\n");
      out.write("\t\t<th>암호 : \r\n");
      out.write("\t\t<td><input type=\"password\" name=\"pswd1\" id=\"pswd1\" required/>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<th>암호 확인 : \r\n");
      out.write("\t\t<td><input type=\"password\" name=\"pswd2\" id=\"pswd2\" required onkeyup=\"pwCheck()\"/>\r\n");
      out.write("\t\t\t<span class=\"pwStatus\"></span>\r\n");
      out.write("\t</tr> */\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
